export const USER_REGISTER = 'USER_REGISTER';
export type USER_REGISTER = typeof USER_REGISTER;

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export type USER_REGISTER_SUCCESS = typeof USER_REGISTER_SUCCESS;

export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export type USER_REGISTER_FAILED = typeof USER_REGISTER_FAILED;

export const USER_LOGIN = 'USER_LOGIN';
export type USER_LOGIN = typeof USER_LOGIN;

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export type USER_LOGIN_SUCCESS = typeof USER_LOGIN_SUCCESS;

export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export type USER_LOGIN_FAILED = typeof USER_LOGIN_FAILED;
