export const USER_REGISTER = 'USER_REGISTER';
export type USER_REGISTER = typeof USER_REGISTER;

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export type USER_REGISTER_SUCCESS = typeof USER_REGISTER_SUCCESS;

export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export type USER_REGISTER_FAILED = typeof USER_REGISTER_FAILED;

export const USER_LOGIN = 'USER_LOGIN';
export type USER_LOGIN = typeof USER_LOGIN;

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export type USER_LOGIN_SUCCESS = typeof USER_LOGIN_SUCCESS;

export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export type USER_LOGIN_FAILED = typeof USER_LOGIN_FAILED;

export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export type USER_RESET_PASSWORD = typeof USER_RESET_PASSWORD;

export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export type USER_RESET_PASSWORD_SUCCESS = typeof USER_RESET_PASSWORD_SUCCESS;

export const USER_RESET_PASSWORD_FAILED = 'USER_RESET_PASSWORD_FAILED';
export type USER_RESET_PASSWORD_FAILED = typeof USER_RESET_PASSWORD_FAILED;

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export type USER_CHANGE_PASSWORD = typeof USER_CHANGE_PASSWORD;

export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export type USER_CHANGE_PASSWORD_SUCCESS = typeof USER_CHANGE_PASSWORD_SUCCESS;

export const USER_CHANGE_PASSWORD_FAILED = 'USER_CHANGE_PASSWORD_FAILED';
export type USER_CHANGE_PASSWORD_FAILED = typeof USER_CHANGE_PASSWORD_FAILED;

export const FETCH_USER = 'FETCH_USER';
export type FETCH_USER = typeof FETCH_USER;
