export const USER_REGISTER = 'USER_REGISTER';
export type USER_REGISTER = typeof USER_REGISTER;

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export type USER_REGISTER_SUCCESS = typeof USER_REGISTER_SUCCESS;

export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export type USER_REGISTER_FAILED = typeof USER_REGISTER_FAILED;

export const USER_LOGIN = 'USER_LOGIN';
export type USER_LOGIN = typeof USER_LOGIN;

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export type USER_LOGIN_SUCCESS = typeof USER_LOGIN_SUCCESS;

export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export type USER_LOGIN_FAILED = typeof USER_LOGIN_FAILED;

export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export type USER_RESET_PASSWORD = typeof USER_RESET_PASSWORD;

export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export type USER_RESET_PASSWORD_SUCCESS = typeof USER_RESET_PASSWORD_SUCCESS;

export const USER_RESET_PASSWORD_FAILED = 'USER_RESET_PASSWORD_FAILED';
export type USER_RESET_PASSWORD_FAILED = typeof USER_RESET_PASSWORD_FAILED;

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export type USER_CHANGE_PASSWORD = typeof USER_CHANGE_PASSWORD;

export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export type USER_CHANGE_PASSWORD_SUCCESS = typeof USER_CHANGE_PASSWORD_SUCCESS;

export const USER_CHANGE_PASSWORD_FAILED = 'USER_CHANGE_PASSWORD_FAILED';
export type USER_CHANGE_PASSWORD_FAILED = typeof USER_CHANGE_PASSWORD_FAILED;

export const USER_EMAIL_ACTIVATION = 'USER_EMAIL_ACTIVATION';
export type USER_EMAIL_ACTIVATION = typeof USER_EMAIL_ACTIVATION;

export const USER_EMAIL_ACTIVATION_SUCCESS = 'USER_EMAIL_ACTIVATION_SUCCESS';
export type USER_EMAIL_ACTIVATION_SUCCESS = typeof USER_EMAIL_ACTIVATION_SUCCESS;

export const USER_EMAIL_ACTIVATION_FAILED = 'USER_EMAIL_ACTIVATION_FAILED';
export type USER_EMAIL_ACTIVATION_FAILED = typeof USER_EMAIL_ACTIVATION_FAILED;

export const FETCH_USER = 'FETCH_USER';
export type FETCH_USER = typeof FETCH_USER;

export const USER_INVITE = 'USER_INVITE';
export type USER_INVITE = typeof USER_INVITE;

export const USER_INVITE_SUCCESS = 'USER_INVITE_SUCCESS';
export type USER_INVITE_SUCCESS = typeof USER_INVITE_SUCCESS;

export const USER_INVITE_FAILED = 'USER_INVITE_FAILED';
export type USER_INVITE_FAILED = typeof USER_INVITE_FAILED;
