language: node_js
dist: trusty
sudo: true

cache:
  directories:
    - $HOME/google-cloud-sdk

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - ZONE=europe-west3-b
    - PROJECT=observer-215008
  
before_install:
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version

jobs:
  include:
    - stage: build docker image
      script: bash ./job.sh
      
branches:
  only:
    - logview
    - raw-store
    - aggregated-store

deploy:
  - provider: script
    script: bash ./deploy.sh
    skip_cleanup: true
    on:
      all_branches: true