language: node_js
dist: trusty
sudo: true

cache:
  directories:
    - $HOME/google-cloud-sdk

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - ZONE=europe-west3-b
    - PROJECT=observer-215008
  
before_install:
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version

jobs:
  include:
    if: branch = logview
    env: PROJECT_NAME=logview
    if: branch = aggregated-store
    env: PROJECT_NAME=aggregatedstorage
    if: branch = raw-store
    env: PROJECT_NAME=rawstorage
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $PROJECT_NAME ./$PROJECT_NAME
        - docker tag $PROJECT_NAME $DOCKER_USERNAME/$PROJECT_NAME
        - docker push $DOCKER_USERNAME/$PROJECT_NAME
branches:
  only:
    - logview
    - raw-store
    - aggreagted-store

deploy:
  - provider: script
    script: bash ./deploy_raw.sh
    skip_cleanup: true
    on:
      branch: raw-store
  - provider: script
    script: bash ./deploy_logview.sh
    skip_cleanup: true
    on:
      branch: logview
  - provider: script
    script: bash ./deploy_aggregated.sh
    skip_cleanup: true
    on:
      branch: aggregated-store