#!/bin/sh
export NODE_ENV=development

export POSTGRES_EXTERNAL_PORT=5432
export POSTGRES_INTERNAL_PORT=5432
export POSTGRES_DB=observer-postgres
export POSTGRES_USER=root
export POSTGRES_PWD=qwerty

export PG_ADMIN_DEFAULT_USER=user@domain.com
export PG_ADMIN_DEFAULT_PASSWROD=SuperSecret
export PG_ADMIN_EXTERNAL_PORT=5050
export PG_ADMIN_INTERNAL_PORT=80

export APP_PORT=3060

export RAW_DB_EXTERNAL_PORT=27017
export RAW_DB_INTERNAL_PORT=27017

export AGGREGATED_DB_EXTERNAL_PORT=27018
export AGGREGATED_DB_INTERNAL_PORT=27017

docker-compose up --build -d