export const FETCH_COMPANY_USERS = 'FETCH_COMPANY_USERS';
export type FETCH_COMPANY_USERS = typeof FETCH_COMPANY_USERS;

export const FETCH_COMPANY_USERS_SUCCESS = 'FETCH_COMPANY_USERS_SUCCESS';
export type FETCH_COMPANY_USERS_SUCCESS = typeof FETCH_COMPANY_USERS_SUCCESS;

export const FETCH_COMPANY_USERS_FAILED = 'FETCH_COMPANY_USERS_FAILED';
export type FETCH_COMPANY_USERS_FAILED = typeof FETCH_COMPANY_USERS_FAILED;

export const USER_CHANGE_COMPANY = 'USER_CHANGE_COMPANY';
export type USER_CHANGE_COMPANY = typeof USER_CHANGE_COMPANY;

export const USER_CHANGE_COMPANY_SUCCESS = 'USER_CHANGE_COMPANY_SUCCESS';
export type USER_CHANGE_COMPANY_SUCCESS = typeof USER_CHANGE_COMPANY_SUCCESS;

export const USER_CHANGE_COMPANY_FAILED = 'USER_CHANGE_COMPANY_FAILED';
export type USER_CHANGE_COMPANY_FAILED = typeof USER_CHANGE_COMPANY_FAILED;
