export const FETCH_COMPANY_USERS = 'FETCH_COMPANY_USERS';
export type FETCH_COMPANY_USERS = typeof FETCH_COMPANY_USERS;

export const FETCH_COMPANY_USERS_SUCCESS = 'FETCH_COMPANY_USERS_SUCCESS';
export type FETCH_COMPANY_USERS_SUCCESS = typeof FETCH_COMPANY_USERS_SUCCESS;

export const FETCH_COMPANY_USERS_FAILED = 'FETCH_COMPANY_USERS_FAILED';
export type FETCH_COMPANY_USERS_FAILED = typeof FETCH_COMPANY_USERS_FAILED;
