export const CHANGE_SERVER_SETTINGS = 'CHANGE_SERVER_SETTINGS';
export type CHANGE_SERVER_SETTINGS = typeof CHANGE_SERVER_SETTINGS;

export const CHANGE_SERVER_SETTINGS_SUCCESS = 'CHANGE_SERVER_SETTINGS_SUCCESS';
export type CHANGE_SERVER_SETTINGS_SUCCESS = typeof CHANGE_SERVER_SETTINGS_SUCCESS;

export const CHANGE_SERVER_SETTINGS_FAILED = 'CHANGE_SERVER_SETTINGS_FAILED';
export type CHANGE_SERVER_SETTINGS_FAILED = typeof CHANGE_SERVER_SETTINGS_FAILED;

export const FETCH_SERVER_SETTINGS = 'FETCH_SERVER_SETTINGS';
export type FETCH_SERVER_SETTINGS = typeof FETCH_SERVER_SETTINGS;

export const FETCH_SERVER_SETTINGS_SUCCESS = 'FETCH_SERVER_SETTINGS_SUCCESS';
export type FETCH_SERVER_SETTINGS_SUCCESS = typeof FETCH_SERVER_SETTINGS_SUCCESS;

export const FETCH_SERVER_SETTINGS_FAILED = 'FETCH_SERVER_SETTINGS_FAILED';
export type FETCH_SERVER_SETTINGS_FAILED = typeof FETCH_SERVER_SETTINGS_FAILED;
