version: "2.0"
services:
  app:
      build: .
      command: yarn start
      links: 
        - raw-storage-db
  raw-storage-db:
      container_name: rawstore
      image: mongo
      volumes:
        - /home/rawdb/raw_mongovolume:/data/db
      ports:
        - ${RAW_DB_EXTERNAL_PORT}:${RAW_DB_INTERNAL_PORT}
  rabbitmq:
      container_name: queue
      image: rabbitmq:3-management
      ports:
        - ${RABBITMQ_EXTERNAL_PORT}:${RABBITMQ_INTERNAL_PORT}
networks:
  raw-storage-db:
    driver: bridge