export const ADD_NEW_APP = 'ADD_NEW_APP';
export type ADD_NEW_APP = typeof ADD_NEW_APP;

export const ADD_NEW_APP_SUCCESS = 'ADD_NEW_APP_SUCCESS';
export type ADD_NEW_APP_SUCCESS = typeof ADD_NEW_APP_SUCCESS;

export const ADD_NEW_APP_FAILED = 'ADD_NEW_APP_FAILED';
export type ADD_NEW_APP_FAILED = typeof ADD_NEW_APP_FAILED;

export const UPDATE_APP = 'UPDATE_APP';
export type UPDATE_APP = typeof UPDATE_APP;

export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS';
export type UPDATE_APP_SUCCESS = typeof UPDATE_APP_SUCCESS;

export const UPDATE_APP_FAILED = 'UPDATE_APP_FAILED';
export type UPDATE_APP_FAILED = typeof UPDATE_APP_FAILED;

export const DELETE_APP = 'DELETE_APP';
export type DELETE_APP = typeof DELETE_APP;

export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS';
export type DELETE_APP_SUCCESS = typeof DELETE_APP_SUCCESS;

export const DELETE_APP_FAILED = 'DELETE_APP_FAILED';
export type DELETE_APP_FAILED = typeof DELETE_APP_FAILED;

export const FETCH_APPS_LIST = 'FETCH_APPS_LIST';
export type FETCH_APPS_LIST = typeof FETCH_APPS_LIST;

export const FETCH_APPS_LIST_SUCCESS = 'FETCH_APPS_LIST_SUCCESS';
export type FETCH_APPS_LIST_SUCCESS = typeof FETCH_APPS_LIST_SUCCESS;

export const FETCH_APPS_LIST_FAILED = 'FETCH_APPS_LIST_FAILED';
export type FETCH_APPS_LIST_FAILED = typeof FETCH_APPS_LIST_FAILED;
