export const ADD_NEW_APP = 'ADD_NEW_APP';
export type ADD_NEW_APP = typeof ADD_NEW_APP;

export const ADD_NEW_APP_SUCCESS = 'ADD_NEW_APP_SUCCESS';
export type ADD_NEW_APP_SUCCESS = typeof ADD_NEW_APP_SUCCESS;

export const ADD_NEW_APP_FAILED = 'ADD_NEW_APP_FAILED';
export type ADD_NEW_APP_FAILED = typeof ADD_NEW_APP_FAILED;

export const FETCH_APPS_LIST = 'FETCH_APPS_LIST';
export type FETCH_APPS_LIST = typeof FETCH_APPS_LIST;

export const FETCH_APPS_LIST_SUCCESS = 'FETCH_APPS_LIST_SUCCESS';
export type FETCH_APPS_LIST_SUCCESS = typeof FETCH_APPS_LIST_SUCCESS;

export const FETCH_APPS_LIST_FAILED = 'FETCH_APPS_LIST_FAILED';
export type FETCH_APPS_LIST_FAILED = typeof FETCH_APPS_LIST_FAILED;
