version: "3"
services:
  app:
    build: .
    volumes:
      - "./:/src/"
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PWD}@postgres/${POSTGRES_DB}
    command: /src/node_modules/.bin/nodemon --legacy-watch /src/backend/server.js
    links:
        - mongo
        - postgres:postgres
    networks:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    container_name: logview-postgres
    working_dir: /src/
    # volumes:
    #   - ./postgresdata:/src/postgresdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
  pgadmin:
    container_name: observer-pgadmin
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/src/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_DEFAULT_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_DEFAULT_PASSWROD}
      # - PGADMIN_ENABLE_TLS=True
    links:
      - postgres:postgres
    ports:
      - ${PG_ADMIN_EXTERNAL_PORT}:${PG_ADMIN_INTERNAL_PORT}
    networks:
      - postgres
    restart: unless-stopped
  mongo:
      container_name: logview-mongo
      image: mongo
      volumes:
        - ./mongovolume:/data/db"
      ports:
        - ${MONGO_DB_EXTERNAL_PORT}:${MONGO_DB_INTERNAL_PORT}
networks:
  postgres:
    driver: bridge