version: "3"
services:
    app:
      build: .
      volumes:
        - "./:/src/"
      ports:
        - 3060:3060
      # command: ls
      command: /src/node_modules/.bin/nodemon --legacy-watch /src/backend/server.js