export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export type CHANGE_SETTINGS = typeof CHANGE_SETTINGS;

export const CHANGE_SETTINGS_SUCCESS = 'CHANGE_SETTINGS_SUCCESS';
export type CHANGE_SETTINGS_SUCCESS = typeof CHANGE_SETTINGS_SUCCESS;

export const CHANGE_SETTINGS_FAILED = 'CHANGE_SETTINGS_FAILED';
export type CHANGE_SETTINGS_FAILED = typeof CHANGE_SETTINGS_FAILED;

export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export type FETCH_SETTINGS = typeof FETCH_SETTINGS;

export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export type FETCH_SETTINGS_SUCCESS = typeof FETCH_SETTINGS_SUCCESS;

export const FETCH_SETTINGS_FAILED = 'FETCH_SETTINGS_FAILED';
export type FETCH_SETTINGS_FAILED = typeof FETCH_SETTINGS_FAILED;
