module.exports = {
  CPU_APP: 'CPU_APP',
  CPU_SERVER: 'CPU_SERVER',
  MEMORY_SERVER: 'MEMORY_SERVER',
  MEMORY_APP: 'MEMORY_APP',
  HTTP_STATS: 'HTTP_STATS',
  SOCKETS_STATS: 'SOCKETS_STATS',
  LOG: 'LOG',
  NOTIFICATION: 'NOTIFICATION'
};
